language: ruby
script: "./build.sh"
branches:
  only:
  - develop
  - /^feature\/.*$/
rvm:
- 2.1.2
env:
  global:
    secure: do61KPHZC0CN/JIFFY1fLKs1Z4aP8GKzAnxprE0nlyomS8N6xAl1RV6OTSe4ryVCpLm7k5aZ/39x5w8vKUCJSRWpi4XZIz0Fpl/k38/evCWwNqYhK6O1cV8igj+4tsLT90oeeHLlr8ugMMnyQeSeGhOVIQPMhotF2VwMBl88aA6Ts6loa7UUKhExuTGwBEqbd32Q6+1f1MgUQnn5vBolayswQo2N5ve5Hx9Kd45FGOmZ4bM3XcDcAAf7PsckDWR8OVN4KueAD+6rw0tmd5KipXzmizn0JVvoeAU76IIRpTxcpH3NKwtYJGX+AS4NEZ3RwVN+Ra5h/x6tYEWJQ1lCSgxJ3oVSjK8OA5jaw7HU1DAh2Hv/QcrVxzUwUi+f2MH5ExNE+/tjAN/PKLgesSceglvNtZ7mB3RfQt4Os29Ut6zJMJy0h8goKMkJdDRRF6CvK2+8diDNpsOKwuTx7HhPtG4QgRwJ7+ke4EyjqDk02BMl26mW9F2PcCgPJqv8XGa/pKdrcz5m2Tv39Ojpz5BMtA34gJBJm73NxlnMp8HFNFjVBe5lQYQPiJoj3kFL2gEI3PbQLb2Rqaq6si0o2W3qBq/pLGt0gm85Pngx4qP/cxwFCqrTujcSm44z/UC44G9Qu1YQ0Fa5COam3YnYmHWqBuB3fBL/roZVOHMCfv0Bzt0=
